version: '3.7'

services:
  mysql-storage:
    build:
      context: mysql
      dockerfile: Dockerfile
    image: mysql:sharding
    container_name: mysql-storage
    restart: unless-stopped
    command: >
      --general-log=ON
      --log-queries-not-using-indexes=ON
      --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: social-network
    networks:
      - stage_network
    volumes:
      - mysql-storage-data:/var/lib/mysql
      - mysql-storage-log:/var/log/mysql

  ch-cluster:
    image: yandex/clickhouse-server:20.6.6.7
    container_name: ch-cluster
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ch-cluster-data:/opt/clickhouse/data
      - ./clickhouse/cluster/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/cluster/users.xml:/etc/clickhouse-server/users.xml
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - ch-shard-1
      - ch-shard-2
      - ch-shard-3
    networks:
      - stage_network

  ch-shard-0:
    image: yandex/clickhouse-server:20.6.6.7
    container_name: ch-shard-0
    volumes:
      - ch-shard-0-data:/opt/clickhouse/data
      - ./clickhouse/shard/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/shard/users.xml:/etc/clickhouse-server/users.xml
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - stage_network

  ch-shard-1:
    image: yandex/clickhouse-server:20.6.6.7
    container_name: ch-shard-1
    volumes:
      - ch-shard-1-data:/opt/clickhouse/data
      - ./clickhouse/shard/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/shard/users.xml:/etc/clickhouse-server/users.xml
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - stage_network

  ch-shard-2:
    image: yandex/clickhouse-server:20.6.6.7
    container_name: ch-shard-2
    volumes:
      - ch-shard-2-data:/opt/clickhouse/data
      - ./clickhouse/shard/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/shard/users.xml:/etc/clickhouse-server/users.xml
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - stage_network

  ch-shard-3:
    image: yandex/clickhouse-server:20.6.6.7
    container_name: ch-shard-3
    volumes:
      - ch-shard-3-data:/opt/clickhouse/data
      - ./clickhouse/shard/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/shard/users.xml:/etc/clickhouse-server/users.xml
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - stage_network

  ch-shard-4:
    image: yandex/clickhouse-server:20.6.6.7
    container_name: ch-shard-4
    volumes:
      - ch-shard-4-data:/opt/clickhouse/data
      - ./clickhouse/shard/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/shard/users.xml:/etc/clickhouse-server/users.xml
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - stage_network

  mysql-migrator:
    build:
      context: ../tools/migrator
      dockerfile: Dockerfile
    image: mysql-migrator:sharding
    container_name: mysql-migrator
    environment:
      MIGRATIONS_PATH: "./migrations"
      DSN: "user:password@tcp(mysql-storage:3306)/social-network"
      OPERATION: "up"
    volumes:
      - ./backend/migrations/mysql:/app/migrations
    networks:
      - stage_network
    depends_on:
      - mysql-storage

  ch-cluster-migrator:
    build:
      context: ../tools/ch-migrator
      dockerfile: Dockerfile
    image: ch-migrator:sharding
    container_name: ch-cluster-migrator
    environment:
      MIGRATIONS_PATH: "./migrations"
      DSN: "clickhouse://ch-cluster:9000?database=default&username=default&password=password&x-multi-statement=true"
      OPERATION: "up"
    volumes:
      - ./backend/migrations/clickhouse/cluster:/app/migrations
    networks:
      - stage_network
    depends_on:
      - ch-cluster

  ch-shard-migrator-0:
    build:
      context: ../tools/ch-migrator
      dockerfile: Dockerfile
    image: ch-migrator:sharding
    container_name: ch-migrator-0
    environment:
      MIGRATIONS_PATH: "./migrations"
      DSN: "clickhouse://ch-shard-0:9000?database=default&username=default&password=password&x-multi-statement=true"
      OPERATION: "up"
    volumes:
      - ./backend/migrations/clickhouse/shard:/app/migrations
    networks:
      - stage_network
    depends_on:
      - ch-shard-0

  ch-shard-migrator-1:
    build:
      context: ../tools/ch-migrator
      dockerfile: Dockerfile
    image: ch-migrator:sharding
    container_name: ch-migrator-1
    environment:
      MIGRATIONS_PATH: "./migrations"
      DSN: "clickhouse://ch-shard-1:9000?database=default&username=default&password=password&x-multi-statement=true"
      OPERATION: "up"
    volumes:
      - ./backend/migrations/clickhouse/shard:/app/migrations
    networks:
      - stage_network
    depends_on:
      - ch-shard-1

  ch-shard-migrator-2:
    build:
      context: ../tools/ch-migrator
      dockerfile: Dockerfile
    image: ch-migrator:sharding
    container_name: ch-migrator-2
    environment:
      MIGRATIONS_PATH: "./migrations"
      DSN: "clickhouse://ch-shard-2:9000?database=default&username=default&password=password&x-multi-statement=true"
      OPERATION: "up"
    volumes:
      - ./backend/migrations/clickhouse/shard:/app/migrations
    networks:
      - stage_network
    depends_on:
      - ch-shard-2

  ch-shard-migrator-3:
    build:
      context: ../tools/ch-migrator
      dockerfile: Dockerfile
    image: ch-migrator:sharding
    container_name: ch-migrator-3
    environment:
      MIGRATIONS_PATH: "./migrations"
      DSN: "clickhouse://ch-shard-3:9000?database=default&username=default&password=password&x-multi-statement=true"
      OPERATION: "up"
    volumes:
      - ./backend/migrations/clickhouse/shard:/app/migrations
    networks:
      - stage_network
    depends_on:
      - ch-shard-3

  ch-shard-migrator-4:
    build:
      context: ../tools/ch-migrator
      dockerfile: Dockerfile
    image: ch-migrator:sharding
    container_name: ch-migrator-4
    environment:
      MIGRATIONS_PATH: "./migrations"
      DSN: "clickhouse://ch-shard-4:9000?database=default&username=default&password=password&x-multi-statement=true"
      OPERATION: "up"
    volumes:
      - ./backend/migrations/clickhouse/shard:/app/migrations
    networks:
      - stage_network
    depends_on:
      - ch-shard-4

  redis:
    build:
      context: redis
      dockerfile: Dockerfile
    container_name: redis_sharding
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - stage_network

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend:sharding
    container_name: backend_sharding
    ports:
      - '9999:9999'
    environment:
      - ADDR=0.0.0.0:9999
      - STORAGE_DSN=user:password@tcp(mysql-storage:3306)/social-network?parseTime=true
      - CH_DSN=tcp://ch-cluster:9000?database=default&username=default&password=password
      - CACHE_ADDR=redis_sharding:6379
      - CACHE_PASSWORD=password
      - CACHE_DB=0
      - JWT_SECRET=secret
      - JWT_ACCESS_TOKEN_TIME_EXPIRE=1h
      - JWT_REFRESH_TOKEN_TIME_EXPIRE=24h
      - SHARDING_COUNT_NODES=2
      - SHARDING_LADY_GAGA_SHARD_ID=4
      - SHARDING_MAX_MSG_FREQ=10
    restart: unless-stopped
    networks:
      - stage_network
    depends_on:
      - mysql-storage
      - ch-cluster
      - redis

volumes:
  ch-cluster-data:
  ch-shard-0-data:
  ch-shard-1-data:
  ch-shard-2-data:
  ch-shard-3-data:
  ch-shard-4-data:
  mysql-storage-data:
  mysql-storage-log:
  redis-data:

networks:
  stage_network:
    name: stage_network
    driver: bridge