version: '3.7'

services:
  storage:
    image: mysql
    container_name: storage_stage
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: social-network
    networks:
      - stage_network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - '8080:8080'
    depends_on:
      - storage
    networks:
      - stage_network

  social_network:
    build:
      context: ..
      dockerfile: deployments/server/Dockerfile
    image: social_network:stage
    container_name: social_network_stage
    ports:
      - '9999:9999'
    environment:
      - ADDR=0.0.0.0:9999
      - STORAGE_DSN=user:password@tcp(storage_stage:3306)/social-network
    networks:
      - stage_network
    depends_on:
      - storage
      - adminer

networks:
  stage_network:
    name: stage_network
    driver: bridge