version: '3.7'

services:
  storage_1:
    image: mysql
    container_name: storage_stage_1
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: social-network
    networks:
      - stage_network
  storage_2:
    image: mysql
    container_name: storage_stage_2
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: social-network
    networks:
      - stage_network
  storage_3:
    image: mysql
    container_name: storage_stage_3
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: social-network
    networks:
      - stage_network

networks:
  stage_network:
    name: stage_network
    driver: bridge