addr: ":9999"

storage:
  dsn: "user:password@tcp(127.0.0.1:3306)/social-network?parseTime=true"
  conn_max_lifetime: "3m"
  max_open_conns: 10
  max_idle_conns: 10

tarantool:
  host: "localhost"
  port: 3301
  user: "user"
  password: "password"
  space: "user"

jwt:
  secret: "some_secret"
  access_token_time_expire: "1h"
  refresh_token_time_expire: "24h"