version: '3.7'

services:
  storage_mysql:
    image: mysql:5.7
    container_name: storage_mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: social-network
    networks:
      - stage_network

  storage_tarantool:
    image: tarantool/tarantool:1.10.0
    container_name: storage_tarantool
    ports:
      - '3301:3301'
    environment:
      TARANTOOL_USER_NAME: user
      TARANTOOL_USER_PASSWORD: password
    networks:
      - stage_network

  replicator:
    build:
      context: replicator
      dockerfile: Dockerfile
    image: replicator
    container_name: replicator
    privileged: true
    networks:
      - stage_network

  backend_with_master_node:
    build:
      context: ../../server
      dockerfile: Dockerfile
    image: social_network_backend:stage
    container_name: backend_with_master_node
    ports:
      - '9999:9999'
    environment:
      - ADDR=0.0.0.0:9999
      - STORAGE_DSN=user:password@tcp(storage_master:3306)/social-network?parseTime=true
      - JWT_SECRET=secret
      - JWT_ACCESS_TOKEN_TIME_EXPIRE=1h
      - JWT_REFRESH_TOKEN_TIME_EXPIRE=24h
    networks:
      - stage_network
#    depends_on:
#      - storage_master
#      - storage_slave_1
#      - storage_slave_2

  backend_with_slave_node:
    build:
      context: ../../server
      dockerfile: Dockerfile
    image: social_network_backend:stage
    container_name: backend_with_slave_node
    ports:
      - '9999:9999'
    environment:
      - ADDR=0.0.0.0:9999
      - STORAGE_DSN=user:password@tcp(storage_slave_1:3306)/social-network?parseTime=true
      - JWT_SECRET=secret
      - JWT_ACCESS_TOKEN_TIME_EXPIRE=1h
      - JWT_REFRESH_TOKEN_TIME_EXPIRE=24h
    networks:
      - stage_network
#    depends_on:
#      - storage_master
#      - storage_slave_1
#      - storage_slave_2

networks:
  stage_network:
    name: stage_network
    driver: bridge