version: '3.7'

services:
  storage_master:
    image: mysql:8.0
    container_name: storage_master
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: social-network
    networks:
      - stage_network

  migrator:
    build:
      context: ../../tools/migrator
      dockerfile: Dockerfile
    image: mysql_migrator:tarantool
    container_name: mysql-migrator-tarantool
    environment:
      MIGRATIONS_PATH: "./migrations"
      DSN: "user:password@tcp(storage_master:3306)/social-network"
      OPERATION: "up"
    volumes:
      - ./backend/migrations:/app/migrations
    networks:
      - stage_network
    depends_on:
      - storage_master

  storage_tarantool:
    image: tarantool/tarantool:2.3.1
    container_name: storage_tarantool
    ports:
      - '3301:3301'
    environment:
      TARANTOOL_USER_NAME: user
      TARANTOOL_USER_PASSWORD: password
    networks:
      - stage_network

  replicator:
    build:
      context: ../../tools/replicator
      dockerfile: Dockerfile
    image: replicator:tarantool
    container_name: replicator
    environment:
      - MYSQL_HOST=storage_master
      - MYSQL_PORT=3306
      - MYSQL_USER=replica
      - MYSQL_PASSWORD=oTUSlave#2020
      - SLAVE_ID=2
      - BINLOG_FILE=mysql-bin.000001
      - BINLOG_POS=665
      - TARANTOOL_HOST=storage_tarantool
      - TARANTOOL_PORT=3301
      - TARANTOOL_USER=user
      - TARANTOOL_PASSWORD=password
      - TARANTOOL_SPACE=user
    networks:
      - stage_network
    depends_on:
      - storage_master
      - storage_tarantool

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend:tarantool
    container_name: backend_tarantool
    ports:
      - '9999:9999'
    environment:
      - ADDR=0.0.0.0:9999
      - STORAGE_DSN=user:password@tcp(storage_master:3306)/social-network?parseTime=true
      - TARANTOOL_HOST=storage_tarantool
      - TARANTOOL_PORT=3301
      - TARANTOOL_USER=user
      - TARANTOOL_PASSWORD=password
      - TARANTOOL_SPACE=user
      - JWT_SECRET=secret
      - JWT_ACCESS_TOKEN_TIME_EXPIRE=1h
      - JWT_REFRESH_TOKEN_TIME_EXPIRE=24h
    networks:
      - stage_network
    depends_on:
      - storage_master
      - storage_tarantool

networks:
  stage_network:
    name: stage_network
    driver: bridge